name: Cv Workflow

on: [push,pull_request]

jobs:
  release:
   runs-on: ubuntu-20.04
   steps: 
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@yv2
      with:
        hugo-version: "latest"
    - name: Build Site
      run: hugo --minify

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
         deploy_key: ${{ secrets.GITHUB_TOKEN}}
         publish_dir: ./public
   
  
   
