name: Cv Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the site 
    - uses: actions/checkout@v2
    - name: Install the dependancies
      run: npm ci
    - name: End message
      run: echo 'All done!'
   
   
