name: Cv Workflow

on: [push,pull_request]

jobs:
  release:
   runs-on: ubuntu-20.04
   steps: 
    - name: Checkout source code
      uses: actions/checkoutv@3
    - name: Install dependancies
      run: npm ci
    - name: End message
      run: echo 'All done!'
   
  
   
